=== Einleitung
Jonathan hat ein Problem: der Direktor hat Dreck über ihn ausgegraben und er weiß nicht, wie er diesen wieder aus der Welt schaffen kann. Wenn er es nicht hinbekommt seine Fassade aufrecht zu erhalten. Denn er ist der Schulsprecher seiner Schule und hat somit ein hohes Ansehen dort. Wenn also herauskommen würde, dass er nur ein Junkie ist, wäre dies nicht nur schlecht für sein Ansehen, sondern auch für das Ansehen der Schule. Als dann auch noch sein eigener Vater im ein Ultimatum stellt wird er nervös. Entweder Jonathan löst das Problem selbst oder sein Vater wird tätig. Zuerst musste er wissen, welchen Dreck hat der Direktor tatsächlich ausgegraben und dann kann er abschätzen, ob es wirklich seine Karriere gefährdet. Zuerst versuchte er es damit, dass er Gespräche des Direktors mit anderen Lehrern und der Abteilungsvorständin mithört und schaut, ob sein Name fällt. Nach mehreren Tagen ist es so, dass er durch Zufall ein Gespräch des Direktors und der Schulärztin belauscht, bei dem es darum geht, was die Schule machen kann, wenn ein Schüler mit Suchtmittel zu tun hat. Somit war ihm klar es ist was Ernstes. Weil er also wusste, dass er es nicht allein schaffen kann, bittet er seinen Vater um seine Unterstützung. 
Sein Vater hat auch gleich eine Idee: 
Ein Gift, welches einen schnellen Tod, ohne großartig äußerliche Verletzungen verursachen. Die Entscheidung fiel auf eine Mischung aus Digitalis und Rohypnol. Das Digitalis führt zu einem schnellen Herzstillstand und das Rohypnol, auch als Roofies bekannt, soll eine Bewusstlosigkeit verursachen. Hierdurch sieht es so aus, als hätte er einen Herzanfall gehabt und nicht das er vergiftet wurde. Somit konnte, nach einiger Vorbereitung, der Plan in die Tat umgesetzt werden und der Plan war wie folgt: Jonathan nutzt seine Position als Schulsprecher, um mit dem Direktor allein zu sprechen. Vorher holt er einen Kaffee und versetzt diesen mit der tödlichen Mischung. Wenn er dann den Direktor sieht, bietet er ihm den Kaffee an. Wenn der Direktor dann schläft, soll er eine SMS an ein PrePaid-Handy senden. Danach soll er einfach gehen und das Schulgebäude durch den Vordereingang verlassen. Vor der Schule wird er dann von einer, vorher bezahlten Männlichen Person, Abgeholt. Dies war der gesamte Plan. Doch was weder der Vater noch Jonathan bedachten war das der Fluchtfahrer es sich anders überlegt und Jonathan für mehr Geld entführt.