=== Der Tatort
Etwa zwei Stunden später findet eine Reinigungskraft den leblosen Direktor und alarmiert sofort die Rettung. Diese kann leider bei Eintreffen nur mehr den Tod feststellen und die Polizei dazu holen. Die nachalarmierte Polizei sperrt sofort den Bereich und sichert schonmal die Ersten möglichen Beweismittel.
Als jedoch dann die Kriminalbeamten auftauchen kommt schon das erste Problem auf. Denn einem der Beamten bringt der Anblick der Leiche Unbehagen. Als der zweite Beamte dies mitbekommt und ebenfalls die Leiche sieht ist kommt es ihm wie die Schuppen von den Augen. „Natürlich wieso habe ich nicht sofort daran gedacht. Der Ort, Der Raum. Ich hätte ihn aufhalten sollen! dachte sich Marko sofort. „Du, Julian ich kann das auch alleine warte erstmal draußen und krieg einen klaren Kopf.“, empfahl er seinem Kollegen, welcher dann auch den Tatort gleich wieder verließ. Also trat Marko, welcher genauso lang wie Julian bei der Polizei arbeitete, Julian aber schon seit Kleinkindertagen kennt, alleine in das Büro des Opfers ein und bewegte sich im selben Schritt zum Gerichtsmediziner, welcher über der bereits auf dem Boden liegenden Leiche beugt und sich etwas auf einem Block notiert. Als dieser aufsah und nur einen Beamten sah(wohlgemerkt er kannte sowohl Julian als auch Marko sehr gut und wusste das Julian eigentlich einen starken Magen hatte), fragte er nur:“ Was ist denn mit dem Kollegen Jüngling los, normalerweise macht ihm das nichts aus?“. Marko hatte jedoch schnell eine Antwort: „Das ist sein Vater.“. Der Schock stand dem Mediziner ins Gesicht geschrieben. Nach einigen Sekunden der Stille kam der Gerichtmediziner wieder zu seinen Worten und gab seine ersten Ergebnisse weiter: „Todeszeitpunkt war, der Lebertemperatur, vor Zwei Stunden. Todesursache war ein Herzinfarkt, genaueres wenn ich ihm am Tisch hatte.“. Marko bedankte sich und bat den Herrn Doktor der Sache Priorität zu geben. Marko der seit etwa zehn Minuten nach seinem Kollegen suchte, fand diesen in einem leeren Klassenraum mit gesenktem Kopf sitzend, die Tränen flossen langsam sein Gesicht und dann den Hals runter. Marko betrat den Raum, ohne ein Wort zu verlieren, etwas zu trinken in der Hand, setzte er sich neben seinen langjährigen Freund und Kollegen und schob die Flasche zu dem von Emotionen gebeutelten Beamten. Dieser bemerkte die Geste und nahm das Getränk, schaute es kurz an und sagte mit einem leichten Lachen auf den Lippen: „was, - kein Doppler?“. Daraufhin lächelten beide. Dieses Lächeln verschwand aber genauso schnell wie es kam und Julian begann laut nachzudenken: „Wer tötet bitte einen Schuldirektor? Sag mir das Bitte. Und wir haben nichts, nicht einmal einen Anhaltspunkt. Ich meine, wir sind seit 10 Jahren bei der Polizei und kennen tun wir uns, seit wir klein waren und bis jetzt gab es an Jedem anderen Tatort wenigstens den Fetzen einer Spur und hier nichts.“. „Das stimmt nicht ganz.“, fuhr Marko dazwischen, „Da ist ein Raum, wo sie die Überwachungsvideos speichern. Problem nur er ist verschlossen.“. „JA UND! DU BIST DOCH STARK ODER. UND WIR SIND POLIZISTEN!“, sagte Julian erfreut. Dies bejahte Marko und so machten sich beide auf den Weg, um das Material zu sichten. – Sie waren auf halber Strecke als Marko plötzlich einen Anruf bekam. “Kriminalpolizei - Groß, guten Tag.“ Antwortete er. Julian stoppte ihn als er das Wort „Entführung“ vernahm und war gespannt wie ein Flitze Bogen zu hören welche Neuigkeiten Marko hatte. „Also – folgendes – Anscheinend wurde der Klassensprecher am helligsten Tag vor dem Schulgebäude entführt. Ich hatte gerade den Vater am Telefon und er hat mir gesagt das sein Sohn sich nicht meldet und auf keine Nachrichten reagiert. – Und nach Angaben des Vaters hatte der Schüler heute in der Früh ein Gespräch mit dem Direktor.“, gab der Beamte mit einem leichten Lächeln wieder. Mit dieser neuen Erkenntnis machten sich die beiden weiter auf dem Weg, um so schnell wie möglich das Material zu sichten. 
An dem Raum angekommen versuchten sie auch gleich die Türe mit Gewalt zu öffnen. Sie versuchten es so lang bis ein Lehrer sie darauf aufmerksam machte sie müssten nur was sagen und er hätte ihnen die Türe aufgesperrt. Beiden stand die Scham ins Gesicht geschrieben als sie die Türe schlussendlich doch ohne Gewalt öffneten und zu einem Terminal sprinteten. Hier konnten sie dann auch schnell das Material sichten und ein Kennzeichen. Nach einer Überprüfung durch die Funkstelle der Polizei über das Zulassungsregister hatte man dann auch einen Namen zu dem Kennzeichen und eine Telefonnummer. Nach einem sehr interessanten Telefonat mit dem Zulassungsbesitzer, bei dem die Beamten erfuhren, dass das Fahrzeug seit längerer Zeit als gestohlen gilt es aber mit einem GPS – Sicherheitssystem ausgestattet ist, wurde eine entsprechende Ortung veranlasst und das Fahrzeug konnte sichergestellt werden und am Fundort konnten weitere Reifenabdrücke gesichert werden und eine Auswertung hat ergeben, dass dieser Reifensatz nur auf Bestellung und nur für einen bestimmten Autotyp erhältlich ist. Nachdem die Fahndung nach einem Solchen Fahrzeug angelaufen war, setzten sich beide in den leeren Klassenraum, welcher ihnen von der Schule auf Wunsch Julians zur Verfügung gestellt wurde und überlegten, wie es weitergeht. Eine Sache, die keinen von beiden in den Sinn gehen möchte, ist die Tatsache, dass warum jemand einen Schüler entführt und einen Direktor umbringt. Die Emotionen waren bei Julian immer noch sehr präsent, somit begann auch nach einigen Minuten des Nachdenkens erneut, bei Julian, Tränen zu fließen und er in eine Schimpftirade  fiel.  Nachdem ihn Marko etwas beruhigen konnte, gab es eine vorerst gute Nachricht: Man konnte mit Hilfe eines Fotos aus dem Überwachungsvideos den Fahrer des Wagens ausforschen. Die schlechte Nachricht das Fahrzeug, samt Fahrer, konnte nicht gefunden werden. Deshalb beschloss Julian gezwungenermaßen den Fall erstmals ruhen zu lassen und der Streifeneinheit die Möglichkeit geben das Fahrzeug zu finden. So machten sich beide wieder auf den Weg zur Dienststelle. 
