=== Eine unerwartete Begegnung
Dort angekommen erwartet sie eine kleine Überraschung:
Eine junge Dame, welche sich als Privatermittlerin vorstellte, fragte nach dem ermittelnden Beamten in dem Fall. Als Julian durch die Türe kommt und dies hört, stellt er sich gleich vor und fragt erstmals nach ihrem Namen und was sie mit dem Verstorbenen oder dem Entführten zu tun hat. Sie beantwortete diese Fragen nur mit Nachdruck und war auch sonst eher zurücklassend. Doch schon im Gespräch mit den beiden Beamten wurde sie etwas lockerer und gab dann auch schnell zu, dass sie auf eigene Faust agiert und leider keinen Auftraggeber hat. Nur warf diese Aussage noch mehr Fragen auf. Also sagten sie ihr sie solle bitte Nachhause gehen und die Beiden würden auf sie zurückkommen. Als sie dann weg war nahm Julian die Gelegenheit beim Schopfe und gab den Namen, welchen sie genannt hat, ins Zentrale Strafregister ein – und tatsächlich, nichts, dann gab er den Namen bei der Sozialversicherung und im Zentralen Melderegister ein – wieder nichts. Tiefer als im Sozialversicherungsregister geht nicht, jedenfalls nicht ohne Richterlichen Beschluss. Bedeutet also diese Person existiert unter diesem Namen nicht. Als nächsten Schritt würde Julian auf den nächsten Tag warten und bei der Adresse vorbeischauen, welche sie genannt hat, würde ihr Büro liegen. Wie zu erwarten war befand sich an dieser Stelle keine Detektei befindet, sondern eine Wäscherei. Das Einzige, was von ihr gestimmt hat, war ihre Telefonnummer. 
Als Julian, Marko damit konfrontierte, konnte auch er nicht verstehen wieso sie hier rein spazierte und behautet sie wäre eine Privatdetektivin. Beide wussten jedoch sie hatte mit dem ganzen irgendetwas zu tun. Gerade deshalb mussten Beide herausfinden wer die Jane Doe  ist und ob sie etwas weiß. Er erzählte Marko jedoch nicht alles. Denn er erzählte Marko nicht, dass die Telefonnummer, welche er von der Frau erhalten hatte, stimmte, somit hatten sie zwar einen Weg, um sie zu kontaktieren, aber sie konnten nicht wissen welche Personen  oder Gruppen vielleicht  mithören.  Also entschied Julian noch zu warten und erst wenn wirklich sicher ist, dass niemand mithört, würde Julian Marko ins gesamte Bild setzen. Trotzdem ließ er sie durch Beamte beschatten, um zum einen sicher zu stellen, dass ihr nichts passiert und zum anderen um zu schauen ob und was sie verbirgt.  Denn wie sich schnell herausstellte ist unsere Jane Doe eine freischaffende Reporterin, welche aus irgendeinem Grund von der Situation erfahren hat. Nach dieser Erkenntnis ließ Julian die Beschattung beenden und begann eine kleine Recherche zu dieser Reporterin. Es gab nur eine Schwierigkeit. Den Der Name, unter dem Sie ihre Geschichten veröffentlicht, ist nicht echt und der Herausgeber der Geschichten will den richtigen Namen nicht sagen.