=== ein freundschaftliches Treffen
Nun musste er zu drastischeren und etwas unorthodoxe Maßnahmen ergreifen. Er rief sie direkt an und lud sie auf ein Abendessen   ein. Also trafen sich die beiden  beim Würstelstand zum scharfen René. Er war einige Minuten früher als sie da und bestellte schon mal für sich einmal Käsekrainer mit Senf und eine Coca Cola. Als dann auch sie eintraf, merkte sie erstmal an, wieso man sich bei einem Würstelstand treffen. Er sagte, dass er sich hier mit ihr treffen wollte, weil er gerne und oft isst. Nach einigen Minuten kam dann plötzlich ein Field Supervisor der Berufsrettung und fragte, ob er sich dazu gesellen kann. Julian, der den Sanitäter kennt, sagte sofort ja. Der Sanitäter fragte auch sogleich woher die beiden sich kennen. Als die Frau jedoch keine Antwort geben konnte fragte der Sanitäter erneut, jedoch ging die Frage diesmal an Julian, der auch eine Antwort parat hatte und sagte das sie eine Zeugin sei, welche sich mit ihm treffen wollte. Der Sanitäter fragte noch ob es denn möglich wäre ein Foto zu machen, um eine Erinnerung an dieses Treffen zu haben. Beide  hatten nichts dagegen einzuwenden und so war  das Foto schnell gemacht.