=== ehemalige Kollegen?
Der SuFi   konnte jedoch nicht lang bleiben und musste auch schon wieder zum nächsten Einsatz düsen.  Was die Dame jedoch nicht wusste, war das Foto eine List des Sanitäters, weil er sie erkannte und sie nun mit anderen Fotos vergleicht.   Noch am selben Abend nach, als er in einem ruhigen Moment wieder in der Wache saß, nutzte er den Moment und verglich besagtes Bild mit  einem Verzeichnis von ehemaligen Mitarbeitern und stößt prompt auch auf die entsprechende Person. 
Caroline Steves, eine Ehemalige Rettungssanitäterin und Seiltechnikerin. Mit dieser Information gewappnet machte sich Klausi wieder auf dem weg, als sein Chef den Raum betritt. 
„Klausi!“, rief er mit freudiger Stimme,“ was machst du so spät noch hier hast du kein Leben?“.
„Du weißt doch ich habe keine Dienstnummer, ich habe eine Inventarnummer.“ Antwortete Klausi auf diese Frage. Dies gefiel Sascha jedoch nicht, da er sofort wusste, dass er ablenken will. „Sind das die neuen Lehrunterlagen, die ich Unterschreiben muss?“ hackte er nach in Bezug auf die Unterlagen, welche er in den Händen hält. „Äh, na das sind nur Formulare, welche ich mir ausgedruckt habe. Die brauche ich für……“, versuchte Klausi auszuweichen. „Nächstes Mal mach das bei dir Zuhause“, erwiderte Sascha mit leicht erzürnter Stimme. Klausi verlies den Raum und machte sich auf den Weg zu Julian, um ihm die Informationen zu geben.
Als Klausi in Julians Büro ankam war dieser gerade in der Kriminaltechnik, um nachzufragen, ob es Erkenntnisse gab. Als er jedoch in sein Büro zurückkam, wunderte er sich über den Besuch und erfragte prompt den Grund dieses Besuchs. „Als wir uns letztens beim Würstler getroffen haben, habe ich ja ein Foto von dieser Zeugin gemacht.“, antwortete er, „das war ein Vorwand, weil ich gewusst habe ich kenne sie von irgendwoher.“. „Okay und woher?“, fragte Julian nach. 
„Sie war früher bei der Berufsrettung Wien war auch ziemlich gut in ihrem Job. Sie hatte sogar die STEG-Ausbildung .“, führte Klausi fort, „Ja, Sie hat bis vor etwas mehr als 10 Jahren bei der Berufsrettung gearbeitet. Ich habe gerade erst bei der Rettung angefangen, aber ich konnte trotzdem ein paar Mal mit ihr zusammengearbeitet.“ „und warum arbeitet sie nichtmehr bei euch?“, fragte Julian. 
„Sie hat vor etwas mehr als 10 Jahren aus freien Stücken gekündigt, nachdem sie jemanden kennengelernt hat.“, erzählte Klausi. „Und zwar von einem Tag auf den anderen“, fuhr er fort.
