=== bewegte Vergangenheit
Nun, dies war zwar Oberflächlich Richtig, aber es ist tatsächlich mehr dahinter als Klausi dachte. Denn es war tatsächlich etwas komplizierter als man denken mag. 
Sie hat nämlich nicht irgendjemanden kennengelernt – sondern Tobias Hess der ältere Bruder von Jonathan und Sohn des Unternehmers Bernd Hess. Doch was viele nicht wissen ist Bernd nicht einfach nur ein Unternehmer, denn er ist auch ein ruchloser Verbrecherboss und Drahtzieher dieses ganzen Komplott. 
Jetzt ist es so, dass Caroline, nachdem sie bei der Berufsrettung kündigte, heiratete sie kurze Zeit später und war auch sehr glücklich damit. Doch nur zwei Jahre später sah es auch wieder anders aus. Denn Sabine, die zu diesem Zeitpunkt von dem kriminellen Nebengeschäft der Familie eingeweiht war, musste dabei zusehen wie ihr geliebter Ehemann auf dem OP Tisch verstirbt. Tobias der als Vollstrecker für seinen Vater arbeitete, wurde bei während einer Verfolgungsjagd mit der Polizei schwer verwundet und konnte zwar noch mit seiner Familie entkommen und konnte Zuhause von Sabine und einem Familienarzt behandelt werden aber seine Verletzungen waren doch zu gravierend. 
Nach dem Tod von Tobias trauerten die anderen, aber Sabine war am Boden zerstört. Sie brach einfach auf dem Boden zusammen und konnte nicht aufhören zu weinen. Das war der Moment für Bernd und er sagte zu ihr, dass es schwer zu verkraften sei, aber er wüsste eine Lösung, die für sie beide von Vorteil wäre. Er würde ihr die Ausbildung geben, die sie braucht, und sie würde für ihn arbeiten - draußen als Agentin. In ihrem geschwächten Zustand und voller Wut akzeptierte sie und das war der Moment, in dem Sabine Steves starb und Caroline Hess geboren wurde. 
Gleich am nächsten Tag fuhr Bernd die beiden zu einem verlassenen Anwesen, wo sie ihre Ausbildung zur Agentin beginnen sollte, und sie war eine eifrige Lernende. 
Ihre Wildheit beim Kämpfen war nur schwach im Vergleich zu ihrer puren Wut, eine Wut, die durch die ständigen Hänseleien des Ausbilders und den Gedanken an ihren verstorbenen Mann noch weiter angeheizt wurde. 
Sie trainierte hart und gewann sehr schnell den Respekt der anderen Agenten im Lager. 
Und die Gelegenheit war nicht weit, Bernd gab ihr den Auftrag, einen Rivalen von ihm zu vernichten. 
Sie tat genau das, ohne zu zögern, ohne Gnade und so kam sie auch zu ihrem Codenamen - Die blonde Witwe (in Anlehnung an die giftige Spinne Schwarze Witwe).  
