=== Der Unfall
Dies konnte Julian nicht ganz glauben, daher fragte er wie sie den hieße. Klausi, der es selber nicht fassen konnte sagte ihm den Namen – Sabine Steves – Julian fragte jetzt noch ob er ein Geburtsdatum wisse, was er mit ja beantwortete. Julian gab sowohl den Namen als auch das Geburtsdatum in das Polizeiliche Personenabfragesystem ein und es lieferte genau einen Eintrag.
Name: Sabine Steves
Geboren: 21.08.1994
Anschrift: Hervicusgasse 27, 1210 Wien
Behördliche Eintragung: 
	Die Person Sabine Steves, geb. 21.08.1994, ist am 16.05.2014 an den Folgen eines 	schweren Verkehrsunfall verstorben. Nähere Informationen im Ermittlungsakt 	Aktenzahl 451783-27314-16052014
Julian zeigte Klausi den Bildschirm und sagte: „Bist du dir sicher, dass es der richtige Name und Geburtsdatum ist weil ich weiß ja nicht was ihr da alles im AKH anstellts, aber ich bin mir sicher sie sieht nicht aus wie eine Tote.“. Klausi, der es selber nicht versteht meint nur, er wüsste genau, dass es sich bei der Frau um seine ehemalige Kollegin handelte. Sie begannen zu diskutieren und beendeten das Gespräch mit der Übereinkunft mit niemanden darüber zu reden, bis sie Klarheit erlangten. Nicht einmal Marko durfte davon erfahren, da er sowieso meinte Julian würde sich da in etwas hineinsteigern somit wenn er erfahren würde, dass sie möglicherweise einer Toten nachjagen würde Marko wohl beide in eine Psychiatrische Abteilung einweisen lassen.
