=== Jonathans Befreiung
Nach einem anonymen Hinweis wird eine Lagerhalle als mögliches Versteck des Entführers ausfindig gemacht werden. Julian und Marko machen sich, mit einem Einsatzkontigent der WEGA und  BE, direkt auf den Weg dorthin, um den vermeintlich entführten Jonathan zu befreien. Am Einsatzort, einige Meter abseits der Lagerhalle, eingetroffen machten sie Sich sofort bereit die Lagerhalle zu stürmen. Klausi, der ,mit einem eigenen Kontigent aus mehreren RTWs und der SEG, ebenfalls bereitsteht kommt ebenfalls zur Einsatzbesprechung dazu und übergibt diese Informationen an seinen Einsatzleiter weiter. Wenige Minuten später machten die Polizeibeamten sich auf den Weg zu der Lagerhalle war totale Stille. Die einzigen Töne, die man hörte waren die Schritte der Einsatzstiefel und der Motor des Survivors, niemand wagte es nur ein Wort von sich zu geben. Diese Stille wurde dann aber auch schnell wieder unterbrochen, als das Kontigent an der Lagerhalle ankam, sich jeweils links und rechts in Position begab, zwei WEGA Beamte die Türklinken der Rolltore griffen und auf das Kommando von Julian hin aufrissen. Mit dem Knall mehrerer Blendgranaten wurde die Stille beendet. Das Einsatzteam stürmte in die Lagerhalle, die eine Hälfte ging nach links, die andere nach rechts und man hörte nurmehr die Beamten rufen: "Polizei - Alle sofort auf den Boden!" und "Polizei - Wer auch immer hier drinnen ist gebt euch zu erkennen!", diese Aufforderungen wurden dann auch mehrmals wiederholt. Bis das Kontigent zu einem Raum kam, welcher wohl als Büro genutzt werden kann. Auch hier stellten sich die Beiden Teams seitlich an der Doppeltür auf, die beiden vordersten Beamten griffen die Türklinken, rissen die Türenflügel auf, und Beamte mit Einsatzschildern (darunter auch Julian) stürmten den Raum. In dem Raum fanden sie einen, an einen Sessel gefesselten Jonathan, welcher nach dieser doch etwas längeren Zeit sehr geschwächt war, und den vermeintlichen Entführer, welcher bereits am Boden kniete und die Hände hinter dem Kopf verschränkte. Dieser wurde sofort von WEGA Beamten zu Boden gerissen und in Handschellen gelegt. Daraufhin folgte das All-Clear von der Polizei und die Sanitäter stürmten in den Raum, um den Jonathan zu versorgen. 
[Ortswechsel: Lagerhalle Außen; ~5-10 Minuten später]
Julian, der seinen Einsatzschild wieder in einem Kleinbus verstaute redete gerade mit Marko und Klausi, als im Hintergrund der Entführer in einem Arrestantenwagen verfrachtet wurde, über die Tatsache, dass dieser Einsatz etwas zu gut verlaufen ist. Klausi antwortete darauf, dass er froh darüber sei, denn je reibungsloser ein derartiger Einsatz verläuft desto weniger Arbeit hat man dann. Marko, auch wenn er es fast nicht glauben konnte, gab Klausi dahingehend recht, indem er sagte, dass je weniger geschossen werden muss, desto weniger Bürokratie bedeutet das für uns alle. 
Julian, der ein bisschen darüber lachte, erkannte auch, dass er sich glücklich schätzen sollte, dass dieser Einsatz so ablief. 
Der Hintergrund des Gesprächs wechselte nebenbei zu Jonathan, welcher auf einer Trage liegend, an einen Monitor angeschlossen und mit einem Zugang im Arm in einen RTW verladen wurde und dann auch direkt in ein nahe gelegenes Krankenhaus gebracht wurde. 
