=== Julians Gefangennahme
Nach einem langen Tag kommt Julian ziemlich erschöpft nach Hause, machte sich einen Kaffee und setzte sich auf seinen Schreibtisch, drehte seinen Computer auf und begann sein übliches Spiel zu zocken. Doch eine Sache blieb ihm die ganze Zeit im Kopf. Er kämpfte immer noch mit dem Gedanken:" wieso verlief die Geiselbefreiung so reibungslos. Der Typ hatte ein Vollautomatisches Sturmgewehr mit drei vollen Magazinen einfach neben sich liegen und doch entschied er sich für die Kapitulation?". Diese Frage stellte er sich die ganze Zeit. Er grübelte noch bis tief in die Nacht bis er sich dazu entschloss dem ganzen nochmals nachzugehen. Also machte er sich Tief in der Nacht nochmals auf dem Weg zu der Lagerhalle, um dort nochmals nachzuschauen. Bei dem Grundstück angekommen entschloss er sich den Rest zu Fuß zu nehmen, um weniger Aufmerksamkeit zu erzeugen. Bei der Lagerhalle angekommen machte er eine Interessante Entdeckung. Mehrere schwarze Fahrzeuge ohne Kennzeichen und mit komplett schwarzen Scheiben stehen vor der Lagerhalle und Räumen diese komplett aus. Als dann auch noch, aus dem Nichts, Sabine auftaucht erschrickt Julian kurz. Julian fragte sie sofort, was sie den hier mache, worauf sie antwortete sie könnte ihn dasselbe fragen. Er sagte ihr er würde nur nochmals nachschauen und verstecke sich hier, um die Lage zu erkunden. Sabine bot ihre Hilfe an. Julian sagte zu ihr Sie müsse für eine Ablenkung sorgen, ohne sich selber in Gefahr zu begeben. Sie entgegnete ein schnelles "Wird gemacht" und verschwindet in einer Dunklen Gasse. Kurz darauf bemerkte Julian, dass die Gegner plötzlich alle aufschreckten und sofort in die Fahrzeuge stiegen und wegfuhren. Julian dachte sich nichts und betrat die Lagerhalle. Mit gezogener Waffe und Taschenlampe schaute er sich nochmals in der Lagerhalle um, wo er nichts fand. Also schaute er sich ebenfalls nochmal in diesem Büro um wo er ein Chaos vorfand. Diese Gestalten haben wohl diesen Raum auf den Kopf gestellt, um irgendetwas zu suchen oder haben sie vielleicht versucht den Raum leer zu räumen. Im nächsten Moment spürte er plötzlich, dass ihm schwindelig wurde und seine Sicht immer verschwommener wurde, bis er kaum noch etwas sehen konnte und er sich nicht einmal auf den Beinen halten konnte. Er konnte nurmehr hören wie eine gedämpfte wohl weibliche Stimme jemanden befahl ihn in zu fesseln, zu knebeln, ihm einen Sack über den Kopf zu ziehen und ihn in einen Transporter zu Laden. Dann wurde alles Schwarz und er verlor das Bewusstsein.  Als er einmal kurz das Bewusstsein wieder erlangte merkte er nur, dass er in einem Fahrzeug war und sich bewegte. Er war komplett erblindet, vermutlich durch eine Augenbinde, das Einzige was ihm irgendetwas sagen konnte waren die Vibrationen des Fahrzeuges und die Regelmäßigen Geräusche eines Funkgerätes jedoch konnte er nicht ausmachen was sie sagen konnten. Doch es war wohl jemand mit Ihm den er merkte das Ihm etwas gespritzt wurde und er schnell wieder das Bewusstsein verlor.