=== Sabines Enthüllung
Nach kurzer Zeit wacht er wieder auf, seine Hände sind um eine Metallstange am Rücken gefesselt und seine Augen sind ebenfalls verbunden. Er merkt jedoch anhand der Vibrationen und der Tatsache der doch immensen Beinfreiheit, dass er sich in einer Transport Maschine befindet. Nach einiger Zeit hört er dann eine Vertraute Stimme und Prompt wird ihm auch schon die Augenbinde vom Gesicht gerissen. Aufgrund des Sedativums konnte er zwar nur verschwommen sehen, aber es reichte, um sein gegenüber zu erkennen. Doch er konnte nichts sagen, bevor er durch einen Schlag ins Gesicht vollständig wach wurde. Vor ihm saß jetzt ein Mann in seinen 50ern mit einen Sekt in der einen Hand und einer Gabel in der anderen. Julian musste noch etwas warten, denn der Schlag hat ihn zwar wach gemacht doch hatte er immer noch ein Ringen in den Ohren.  
 
Nachdem dieses verging begann der Mann zu sprechen und er fragte Julian, was er denn bei der Lagerhalle zu tun hatte. Julian Antwortete so wie es ihm auch schon beim Bundesheer gelernt wurde: "Mein Name ist Julian Jüngling, ich bin Bezirksinspektor beim Koordinierten Kriminaldienst der Landespolizeidirektion Wien. Meine Dienstnummer ist 90-274153." Der Mann, dem diese Antwort nicht gefiel machte eine Geste und schon bekam Julian einen weiteren Schlag. Der Mann wiederholte die Frage und wieder antwortete Julian gleich:" Mein Name ist Julian Jüngling, ich bin …" Dieses Mal konnte Julian den Satz nicht einmal beenden bekam er schon einen dritten Schlag ins Gesicht. Der Mann dem jetzt wohl klar wurde, dass er dies etwas anders angehen sollte begann zu reden:" Okay - Ich sehe das und dies nicht weiter bringt. Wie wäre es so Herr Jüngling, mein Name ist Bernd Hess und meine Mitarbeiterin dürften Sie schon kennen.". In diesem Moment trat eine weitere Figur in sein Blickfeld. Eine etwas Schlankere Frau in einem Schwarz/rotem Overall (ähnlich einer Motorradausrüstung) aus Leder und einer Kapuze, welche einen Schatten auf Ihr durch eine Halbmaske verdecktes Gesicht wirft. Als diese Figur jedoch die Kapuze runterklappte und die Maske vom Gesicht nahm traf es ihn wie einen weiteren Schlag, diesmal jedoch nicht ins Gesicht sondern direkt ins Herz und er Konnte nur ein Wort sagen: "SABINE!?". Ja, es war Sabine, die Frau, welche die ganze Zeit, seitdem dieses ganze Desaster begann bei Ihm war. "Zarić hatte recht, er sagte mir noch mit dir stimmt etwas nicht!" rief er noch mit letzter Kraft. Bernd, der das ganze beobachtete und nebenbei an seinem Teller Äpfel weiter aß, fuhr also weiter:" Jetzt wo wir alle unsere Bekanntschaft gemacht haben reden wir mal Klartext. Sie wissen warum sie wieder bei der Lagerhalle waren und wir wissen es auch. Sie wollten nach Beweisen suchen und hofften etwas zu finden. Leider stießen sie dabei auf unsere Aufräummaßnahmen.". "Dadurch gerieten sie in diese missliche Lage und mich stoßen sie jetzt vor eine schwierige Entscheidung. Soll ich sie am Leben lassen und das Risiko eingehen dass sie, jetzt wo sie meinen Namen kennen, mir noch hartnäckiger Nachjagen oder soll ich sie töten, wie ihren Vater?" erklärte Bernd. Als Julian dies hörte war es komplett vorbei für Ihn. Er war dafür verantwortlich, Er hatte den Tot meines Vater veranlasst. Diese Gedanken fuhren Julian durch den Kopf. Plötzlich hörte man den Piloten über die Lautsprecher:" Sehr geehrte Passagiere - Ich informiere Sie hiermit, dass wir soeben die Nordsee erreicht.". "Tja, dass erleichtert mir die Entscheidung. Sabine würdest du mir die Ehre erweisen und diesen unnötigen Ballast aus dem Flugzeug entfernen." befahl Bernd. Sabine, welche wieder vermummt war nickte nur und begann Julian die Handfesseln abzunehmen und Ihn zur Springertüre an der Seite des Flugzeuges zu Schleifen. Julian, dem sie die Augenbinde wieder draufgab, machte sich mental schon zum Sterben bereit als er ein Seil Spürte und hörte wie sie durch die Maske etwas verzerrt sagte: "Halte es fest wenn du Leben möchtest.". Bevor er dies verarbeiten konnte wurde er schon aus dem Flugzeug gestoßen. Durch die Augenbinde sah er nicht einmal wie hoch er eigentlich war. Einzig und Alleine was er wusste er durfte auf keinen Fall auf dem Rücken oder Bauch aufkommen. Denn egal wie weit oben sie Tatsächlich waren alles über 10 Meter kann in dieser Situation tödlich sein. Er versuchte also mit aller Kraft sein Beine nach unten zu bekommen. Dies gelang ihm zwar aber als er dann auf dem Wasser aufkam schoss sofort ein stechender Schmerz durch seinen ganzen Körper und ohne es zu sehen, wusste er sofort, dass seine Beine gebrochen waren. Er riss sich sofort die Augenbinde vom Kopf und kontrollierte wie schwer sie gebrochen sind. Er sah aber das es sich wohl nur um Knöchelfrakturen handelte. Des Weiteren erinnert er an das Seil, das er immer noch in seiner Hand hält. Als er dieses nach vorne holte merkte er es ist ein Rettungsring. Er versuchte alles, dass er sich auf den Rettungsring legen könnte, um die Gefahr der Unterkühlung zu minimieren. Mit sehr viel Anstrengung schaffte er dies und jetzt hieß es warten. 
Nun schwamm er schon seit mehreren Stunden in der eiskalten Nordsee in dem Rettungsring, den er sich noch schnappen konnte bevor er doch gewaltsam aus den Flugzeug geworfen wurde. Seine Kräfte gingen langsam auch schon zu neige. Die Kälte der Nordsee zieht sich durch seinen ganzen Körper von den Zehenspitzen bis zum letzten haar seines Körpers. Die Minuten vergingen und mit Rettung rechnete er schon lange nicht mehr. Da viel ihm plötzlich ein Piepsen in seiner Schusssicheren Weste auf. Er griff in die Weste und spürte eine kleine Tasche in der Weste und zog ein kleines Gerät hervor. Eine kleine, rechteckige, schwarze Box mit einer roten Lampe und einem kleinen Lautsprecher aus dem das piepsende Geräusch kommt. Als er das Gerät näher inspiziert findet er ein Hersteller Label, welches in das Gehäuse eingraviert ist. Er war zwar schon sehr schwach konnte er nur drei Buchstaben lesen. „GPS“. Als er dies gelesen hat war er überglücklich, denn er wusste irgendjemand weiß wo er ist und kann ihm zur Rettung kommen wird. Diese Rettung kam dann auch nach einigen Stunden in Form eines Hubschraubers der Deutschen Bundespolizei welcher kurz vor ihm zum Stillstand kommt. Der Hubschrauber lässt dann einen Taucher ins Wasser und Erhebt sich dann auf eine Höhe, die es dem Taucher leichter macht zu unserem Held zu gelangen. Als der Taucher dann nach wenigen Minuten bei unserem Helden macht er eine Kurze Voruntersuchung und hängt ihm dann eine Rettungsboa  an. Im selben Moment begab sich in Position, um eine Windenrettung vorzunehmen. Der Taucher hängt also den Karabiner an seiner Weste mit dem Karabiner an der Boa zusammen an den Haken der Winde und signalisiert dem Windenoperator, dass er die Winde hochziehen kann.
Als Julian dann also nach etwa drei Minuten die Schwelle in den Hubschrauber überschreitet wird er sofort auf eine Trage gelegt und festgeschnallt. Ein Sanitäter macht bei ihm sofort einen Zugang und hängt eine vorgewärmte Kochsalzlösung als Infusion an. Ein weiterer Beamter fragt ihn nach seinem Namen und Julian schafft es doch er geschwächt seinen Dienstausweis aus einer weiteren Tasche seine Weste rauszuholen. Der Beamte nimmt den Ausweis entgegen und gibt über seinem Funkgerät dem Schiff von wo der Hubschrauber losgeflogen ist, dass die Zielperson gefunden worden ist und sich sicher im Hubschrauber befindet. Nach diesem Funkspruch setzte sich der Hubschrauber auch gleich in Bewegung und liefert den Geretteten nach etwas mehr als zehn Minuten auf der BP 82 Bamberg ab. 
Auf der Bamberg, einem Einsatzkreuzer der Potsdam Klasse der Deutschen Bundespolizei, angekommen brachte man Julian direkt auf die vorbereitete Krankenstation. Julian war zu diesem Zeitpunkt bereits eingeschlafen und schlief auch über die gesamte fahrt zurück zum Heimathafen des Schiffes.
Als Julian dann doch aus seinem Schlaf erwachte bemerkte er das Marko an seiner Seite saß und wartete bis er aufwachte. Julian, der zu diesem Zeitpunkt noch ziemlich schwach war, brachte nur stammelnd die Worte: „Sie war dort“ und „Sie gehört zu denen“ aus dem Mund, bevor er wieder das Bewusstsein verlor.
An seinem Heimathafen angekommen wurde Julian direkt an den bereits wartenden Rettungshubschrauber Christoph 12, welcher ihn in ein Nahe, gelegenes Krankenhaus brachte. +
"[Zeitsprung: 3 Monate; Ort: Allgemeines Krankenhaus Wien]" +
Julian, der die Letzten Monate seit dem Vorfall, wegen einer Rehab  und Psychologische Betreuung in Krankenstand war hatte am heutigen Tag seine Letzte Therapie-Einheit und Ihm wurde bereits für die nächste Woche für Diensttauglich erklärt. 
[Ort: Allgemeines Krankenhaus Wien Haupteingang]
An diesem Tag holte Marko ihn von seiner Therapie ab. Die beiden verließen das Spital und redeten darüber, was die letzten Monate alles im Dienst passiert ist und wie der Aktuelle Stand der Ermittlungen im Fall Hess ist (Ja, die Ermittlungen zu diesem Fall wurden nach bekannt werden des Vorfalls wieder aufgenommen und diesmal tatsächlich mit Unterstützung des Verfassungsschutzes und des Bundeskriminalamtes. Julian, der sich selber noch nicht ganz im Klaren ist über das Ausmaß dieser Ermittlung, fragt sich aber auch wo das Ganze hinführen soll. Anfangs handelte es sich um eine Ermittlung nach einem Fragwürdigen Todesfall und jetzt ist es eine Behördenübergreifende Ermittlung gegen das Organisierte Verbrechen. 
Die beiden stiegen ins Auto und fuhren zu Julian nach Hause.
